apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::151187558444:role/eksctl-eksctl-demo-nodegroup-ng-a-NodeInstanceRole-1ROW10PMMU9DX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::151187558444:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-24T15:59:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1910"
  uid: 42817442-f113-4ca2-95f6-2dc297b37b6c
