apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::151187558444:role/eksctl-eksctl-demo-nodegroup-ng-2-NodeInstanceRole-PGWRVK799A1G
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::151187558444:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-23T13:58:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1915"
  uid: 73e55915-3860-41a5-8000-71da46a53e5f
